version: '3.9'

services:
  blog:
    image: ${SWARMLET_REGISTRY}/${APP_NAME}:${TAG}
    build:
      context: ./app
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.services.${APP_NAME}.loadbalancer.server.port=${APP_PORT}
        - traefik.http.routers.${APP_NAME}.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.${APP_NAME}.entrypoints=http,https
        - traefik.http.routers.${APP_NAME}.middlewares=redirect@file
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true